-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.19 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for ayantijeevan
DROP DATABASE IF EXISTS `ayantijeevan`;
CREATE DATABASE IF NOT EXISTS `ayantijeevan` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `ayantijeevan`;

-- Dumping structure for table ayantijeevan.aj_login_history
DROP TABLE IF EXISTS `aj_login_history`;
CREATE TABLE IF NOT EXISTS `aj_login_history` (
  `login_his_Id` bigint(40) NOT NULL AUTO_INCREMENT,
  `userLoginId` int(11) NOT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `userAuthToken` varchar(500) NOT NULL,
  `loginTime` datetime DEFAULT NULL,
  `logoutTime` datetime DEFAULT NULL,
  PRIMARY KEY (`login_his_Id`),
  KEY `userLoginId` (`userLoginId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Dumping data for table ayantijeevan.aj_login_history: 0 rows
DELETE FROM `aj_login_history`;
/*!40000 ALTER TABLE `aj_login_history` DISABLE KEYS */;
/*!40000 ALTER TABLE `aj_login_history` ENABLE KEYS */;

-- Dumping structure for table ayantijeevan.aj_state_city_mapping
DROP TABLE IF EXISTS `aj_state_city_mapping`;
CREATE TABLE IF NOT EXISTS `aj_state_city_mapping` (
  `id` bigint(40) NOT NULL AUTO_INCREMENT,
  `state` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `country` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `state` (`state`),
  KEY `country` (`country`),
  KEY `city` (`city`)
) ENGINE=MyISAM AUTO_INCREMENT=1216 DEFAULT CHARSET=latin1;

-- Dumping data for table ayantijeevan.aj_state_city_mapping: 1,215 rows
DELETE FROM `aj_state_city_mapping`;
/*!40000 ALTER TABLE `aj_state_city_mapping` DISABLE KEYS */;
INSERT INTO `aj_state_city_mapping` (`id`, `state`, `city`, `country`) VALUES
	(1, 'Maharashtra', 'Mumbai', 'India'),
	(2, 'Delhi', 'Delhi', 'India'),
	(3, 'Karnataka', 'Bengaluru', 'India'),
	(4, 'Gujarat', 'Ahmedabad', 'India'),
	(5, 'Telangana', 'Hyderabad', 'India'),
	(6, 'TamilNadu', 'Chennai', 'India'),
	(7, 'WestBengal', 'Kolkata', 'India'),
	(8, 'Maharashtra', 'Pune', 'India'),
	(9, 'Rajasthan', 'Jaipur', 'India'),
	(10, 'Gujarat', 'Surat', 'India'),
	(11, 'UttarPradesh', 'Lucknow', 'India'),
	(12, 'UttarPradesh', 'Kanpur', 'India'),
	(13, 'Maharashtra', 'Nagpur', 'India'),
	(14, 'Bihar', 'Patna', 'India'),
	(15, 'MadhyaPradesh', 'Indore', 'India'),
	(16, 'Maharashtra', 'Thane', 'India'),
	(17, 'MadhyaPradesh', 'Bhopal', 'India'),
	(18, 'AndhraPradesh', 'Visakhapatnam', 'India'),
	(19, 'Gujarat', 'Vadodara', 'India'),
	(20, 'UttarPradesh', 'Firozabad', 'India'),
	(21, 'Punjab', 'Ludhiana', 'India'),
	(22, 'Gujarat', 'Rajkot', 'India'),
	(23, 'UttarPradesh', 'Agra', 'India'),
	(24, 'WestBengal', 'Siliguri', 'India'),
	(25, 'Maharashtra', 'Nashik', 'India'),
	(26, 'Haryana', 'Faridabad', 'India'),
	(27, 'Punjab', 'Patiala', 'India'),
	(28, 'UttarPradesh', 'Meerut', 'India'),
	(29, 'Maharashtra', 'Kalyan-Dombivali', 'India'),
	(30, 'Maharashtra', 'Vasai-Virar', 'India'),
	(31, 'UttarPradesh', 'Varanasi', 'India'),
	(32, 'JammuandKashmir', 'Srinagar', 'India'),
	(33, 'Jharkhand', 'Dhanbad', 'India'),
	(34, 'Rajasthan', 'Jodhpur', 'India'),
	(35, 'Punjab', 'Amritsar', 'India'),
	(36, 'Chhattisgarh', 'Raipur', 'India'),
	(37, 'UttarPradesh', 'Allahabad', 'India'),
	(38, 'TamilNadu', 'Coimbatore', 'India'),
	(39, 'MadhyaPradesh', 'Jabalpur', 'India'),
	(40, 'MadhyaPradesh', 'Gwalior', 'India'),
	(41, 'AndhraPradesh', 'Vijayawada', 'India'),
	(42, 'TamilNadu', 'Madurai', 'India'),
	(43, 'Assam', 'Guwahati', 'India'),
	(44, 'Chandigarh', 'Chandigarh', 'India'),
	(45, 'Karnataka', 'Hubli-Dharwad', 'India'),
	(46, 'UttarPradesh', 'Amroha', 'India'),
	(47, 'UttarPradesh', 'Moradabad', 'India'),
	(48, 'Haryana', 'Gurgaon', 'India'),
	(49, 'UttarPradesh', 'Aligarh', 'India'),
	(50, 'Maharashtra', 'Solapur', 'India'),
	(51, 'Jharkhand', 'Ranchi', 'India'),
	(52, 'Punjab', 'Jalandhar', 'India'),
	(53, 'TamilNadu', 'Tiruchirappalli', 'India'),
	(54, 'Odisha', 'Bhubaneswar', 'India'),
	(55, 'TamilNadu', 'Salem', 'India'),
	(56, 'Telangana', 'Warangal', 'India'),
	(57, 'Maharashtra', 'Mira-Bhayandar', 'India'),
	(58, 'Kerala', 'Thiruvananthapuram', 'India'),
	(59, 'Maharashtra', 'Bhiwandi', 'India'),
	(60, 'UttarPradesh', 'Saharanpur', 'India'),
	(61, 'AndhraPradesh', 'Guntur', 'India'),
	(62, 'Maharashtra', 'Amravati', 'India'),
	(63, 'Rajasthan', 'Bikaner', 'India'),
	(64, 'UttarPradesh', 'Noida', 'India'),
	(65, 'Jharkhand', 'Jamshedpur', 'India'),
	(66, 'Chhattisgarh', 'Bhilai Nagar', 'India'),
	(67, 'Odisha', 'Cuttack', 'India'),
	(68, 'Kerala', 'Kochi', 'India'),
	(69, 'Rajasthan', 'Udaipur', 'India'),
	(70, 'Gujarat', 'Bhavnagar', 'India'),
	(71, 'Uttarakhand', 'Dehradun', 'India'),
	(72, 'WestBengal', 'Asansol', 'India'),
	(73, 'Maharashtra', 'Nanded-Waghala', 'India'),
	(74, 'Rajasthan', 'Ajmer', 'India'),
	(75, 'Gujarat', 'Jamnagar', 'India'),
	(76, 'MadhyaPradesh', 'Ujjain', 'India'),
	(77, 'Maharashtra', 'Sangli', 'India'),
	(78, 'UttarPradesh', 'Loni', 'India'),
	(79, 'UttarPradesh', 'Jhansi', 'India'),
	(80, 'Puducherry', 'Pondicherry', 'India'),
	(81, 'AndhraPradesh', 'Nellore', 'India'),
	(82, 'JammuandKashmir', 'Jammu', 'India'),
	(83, 'Karnataka', 'Belagavi', 'India'),
	(84, 'Odisha', 'Raurkela', 'India'),
	(85, 'Karnataka', 'Mangaluru', 'India'),
	(86, 'TamilNadu', 'Tirunelveli', 'India'),
	(87, 'Maharashtra', 'Malegaon', 'India'),
	(88, 'Bihar', 'Gaya', 'India'),
	(89, 'TamilNadu', 'Tiruppur', 'India'),
	(90, 'Karnataka', 'Davanagere', 'India'),
	(91, 'Kerala', 'Kozhikode', 'India'),
	(92, 'Maharashtra', 'Akola', 'India'),
	(93, 'AndhraPradesh', 'Kurnool', 'India'),
	(94, 'Jharkhand', 'Bokaro Steel City', 'India'),
	(95, 'AndhraPradesh', 'Rajahmundry', 'India'),
	(96, 'Karnataka', 'Ballari', 'India'),
	(97, 'Tripura', 'Agartala', 'India'),
	(98, 'Bihar', 'Bhagalpur', 'India'),
	(99, 'Maharashtra', 'Latur', 'India'),
	(100, 'Maharashtra', 'Dhule', 'India'),
	(101, 'Chhattisgarh', 'Korba', 'India'),
	(102, 'Rajasthan', 'Bhilwara', 'India'),
	(103, 'Odisha', 'Brahmapur', 'India'),
	(104, 'Karnataka', 'Mysore', 'India'),
	(105, 'Bihar', 'Muzaffarpur', 'India'),
	(106, 'Maharashtra', 'Ahmednagar', 'India'),
	(107, 'Kerala', 'Kollam', 'India'),
	(108, 'WestBengal', 'Raghunathganj', 'India'),
	(109, 'Chhattisgarh', 'Bilaspur', 'India'),
	(110, 'UttarPradesh', 'Shahjahanpur', 'India'),
	(111, 'Kerala', 'Thrissur', 'India'),
	(112, 'Rajasthan', 'Alwar', 'India'),
	(113, 'AndhraPradesh', 'Kakinada', 'India'),
	(114, 'Telangana', 'Nizamabad', 'India'),
	(115, 'MadhyaPradesh', 'Sagar', 'India'),
	(116, 'Karnataka', 'Tumkur', 'India'),
	(117, 'Haryana', 'Hisar', 'India'),
	(118, 'Haryana', 'Rohtak', 'India'),
	(119, 'Haryana', 'Panipat', 'India'),
	(120, 'Bihar', 'Darbhanga', 'India'),
	(121, 'WestBengal', 'Kharagpur', 'India'),
	(122, 'Mizoram', 'Aizawl', 'India'),
	(123, 'Maharashtra', 'Ichalkaranji', 'India'),
	(124, 'AndhraPradesh', 'Tirupati', 'India'),
	(125, 'Haryana', 'Karnal', 'India'),
	(126, 'Punjab', 'Bathinda', 'India'),
	(127, 'UttarPradesh', 'Rampur', 'India'),
	(128, 'Karnataka', 'Shivamogga', 'India'),
	(129, 'MadhyaPradesh', 'Ratlam', 'India'),
	(130, 'UttarPradesh', 'Modinagar', 'India'),
	(131, 'Chhattisgarh', 'Durg', 'India'),
	(132, 'Meghalaya', 'Shillong', 'India'),
	(133, 'Manipur', 'Imphal', 'India'),
	(134, 'UttarPradesh', 'Hapur', 'India'),
	(135, 'TamilNadu', 'Ranipet', 'India'),
	(136, 'AndhraPradesh', 'Anantapur', 'India'),
	(137, 'Bihar', 'Arrah', 'India'),
	(138, 'Telangana', 'Karimnagar', 'India'),
	(139, 'Maharashtra', 'Parbhani', 'India'),
	(140, 'UttarPradesh', 'Etawah', 'India'),
	(141, 'Rajasthan', 'Bharatpur', 'India'),
	(142, 'Bihar', 'Begusarai', 'India'),
	(143, 'Delhi', 'New Delhi', 'India'),
	(144, 'Bihar', 'Chhapra', 'India'),
	(145, 'AndhraPradesh', 'Kadapa', 'India'),
	(146, 'Telangana', 'Ramagundam', 'India'),
	(147, 'Rajasthan', 'Pali', 'India'),
	(148, 'MadhyaPradesh', 'Satna', 'India'),
	(149, 'AndhraPradesh', 'Vizianagaram', 'India'),
	(150, 'Bihar', 'Katihar', 'India'),
	(151, 'Uttarakhand', 'Hardwar', 'India'),
	(152, 'Haryana', 'Sonipat', 'India'),
	(153, 'TamilNadu', 'Nagercoil', 'India'),
	(154, 'TamilNadu', 'Thanjavur', 'India'),
	(155, 'MadhyaPradesh', 'Murwara (Katni)', 'India'),
	(156, 'WestBengal', 'Naihati', 'India'),
	(157, 'UttarPradesh', 'Sambhal', 'India'),
	(158, 'Gujarat', 'Nadiad', 'India'),
	(159, 'Haryana', 'Yamunanagar', 'India'),
	(160, 'WestBengal', 'English Bazar', 'India'),
	(161, 'AndhraPradesh', 'Eluru', 'India'),
	(162, 'Bihar', 'Munger', 'India'),
	(163, 'Haryana', 'Panchkula', 'India'),
	(164, 'Karnataka', 'Raayachuru', 'India'),
	(165, 'Maharashtra', 'Panvel', 'India'),
	(166, 'Jharkhand', 'Deoghar', 'India'),
	(167, 'AndhraPradesh', 'Ongole', 'India'),
	(168, 'AndhraPradesh', 'Nandyal', 'India'),
	(169, 'MadhyaPradesh', 'Morena', 'India'),
	(170, 'Haryana', 'Bhiwani', 'India'),
	(171, 'Gujarat', 'Porbandar', 'India'),
	(172, 'Kerala', 'Palakkad', 'India'),
	(173, 'Gujarat', 'Anand', 'India'),
	(174, 'Bihar', 'Purnia', 'India'),
	(175, 'WestBengal', 'Baharampur', 'India'),
	(176, 'Rajasthan', 'Barmer', 'India'),
	(177, 'Gujarat', 'Morvi', 'India'),
	(178, 'UttarPradesh', 'Orai', 'India'),
	(179, 'UttarPradesh', 'Bahraich', 'India'),
	(180, 'Rajasthan', 'Sikar', 'India'),
	(181, 'TamilNadu', 'Vellore', 'India'),
	(182, 'MadhyaPradesh', 'Singrauli', 'India'),
	(183, 'Telangana', 'Khammam', 'India'),
	(184, 'Gujarat', 'Mahesana', 'India'),
	(185, 'Assam', 'Silchar', 'India'),
	(186, 'Odisha', 'Sambalpur', 'India'),
	(187, 'MadhyaPradesh', 'Rewa', 'India'),
	(188, 'UttarPradesh', 'Unnao', 'India'),
	(189, 'WestBengal', 'Hugli-Chinsurah', 'India'),
	(190, 'WestBengal', 'Raiganj', 'India'),
	(191, 'Jharkhand', 'Phusro', 'India'),
	(192, 'Jharkhand', 'Adityapur', 'India'),
	(193, 'Kerala', 'Alappuzha', 'India'),
	(194, 'Haryana', 'Bahadurgarh', 'India'),
	(195, 'AndhraPradesh', 'Machilipatnam', 'India'),
	(196, 'UttarPradesh', 'Rae Bareli', 'India'),
	(197, 'WestBengal', 'Jalpaiguri', 'India'),
	(198, 'Gujarat', 'Bharuch', 'India'),
	(199, 'Punjab', 'Pathankot', 'India'),
	(200, 'Punjab', 'Hoshiarpur', 'India'),
	(201, 'JammuandKashmir', 'Baramula', 'India'),
	(202, 'AndhraPradesh', 'Adoni', 'India'),
	(203, 'Haryana', 'Jind', 'India'),
	(204, 'Rajasthan', 'Tonk', 'India'),
	(205, 'AndhraPradesh', 'Tenali', 'India'),
	(206, 'TamilNadu', 'Kancheepuram', 'India'),
	(207, 'Gujarat', 'Vapi', 'India'),
	(208, 'Haryana', 'Sirsa', 'India'),
	(209, 'Gujarat', 'Navsari', 'India'),
	(210, 'Telangana', 'Mahbubnagar', 'India'),
	(211, 'Odisha', 'Puri', 'India'),
	(212, 'Karnataka', 'Robertson Pet', 'India'),
	(213, 'TamilNadu', 'Erode', 'India'),
	(214, 'Punjab', 'Batala', 'India'),
	(215, 'Uttarakhand', 'Haldwani-cum-Kathgodam', 'India'),
	(216, 'MadhyaPradesh', 'Vidisha', 'India'),
	(217, 'Bihar', 'Saharsa', 'India'),
	(218, 'Haryana', 'Thanesar', 'India'),
	(219, 'AndhraPradesh', 'Chittoor', 'India'),
	(220, 'Gujarat', 'Veraval', 'India'),
	(221, 'UttarPradesh', 'Lakhimpur', 'India'),
	(222, 'UttarPradesh', 'Sitapur', 'India'),
	(223, 'AndhraPradesh', 'Hindupur', 'India'),
	(224, 'WestBengal', 'Santipur', 'India'),
	(225, 'WestBengal', 'Balurghat', 'India'),
	(226, 'MadhyaPradesh', 'Ganjbasoda', 'India'),
	(227, 'Punjab', 'Moga', 'India'),
	(228, 'AndhraPradesh', 'Proddatur', 'India'),
	(229, 'Uttarakhand', 'Srinagar', 'India'),
	(230, 'WestBengal', 'Medinipur', 'India'),
	(231, 'WestBengal', 'Habra', 'India'),
	(232, 'Bihar', 'Sasaram', 'India'),
	(233, 'Bihar', 'Hajipur', 'India'),
	(234, 'Gujarat', 'Bhuj', 'India'),
	(235, 'MadhyaPradesh', 'Shivpuri', 'India'),
	(236, 'WestBengal', 'Ranaghat', 'India'),
	(237, 'HimachalPradesh', 'Shimla', 'India'),
	(238, 'TamilNadu', 'Tiruvannamalai', 'India'),
	(239, 'Haryana', 'Kaithal', 'India'),
	(240, 'Chhattisgarh', 'Rajnandgaon', 'India'),
	(241, 'Gujarat', 'Godhra', 'India'),
	(242, 'Jharkhand', 'Hazaribag', 'India'),
	(243, 'AndhraPradesh', 'Bhimavaram', 'India'),
	(244, 'MadhyaPradesh', 'Mandsaur', 'India'),
	(245, 'Assam', 'Dibrugarh', 'India'),
	(246, 'Karnataka', 'Kolar', 'India'),
	(247, 'WestBengal', 'Bankura', 'India'),
	(248, 'Karnataka', 'Mandya', 'India'),
	(249, 'Bihar', 'Dehri-on-Sone', 'India'),
	(250, 'AndhraPradesh', 'Madanapalle', 'India'),
	(251, 'Punjab', 'Malerkotla', 'India'),
	(252, 'UttarPradesh', 'Lalitpur', 'India'),
	(253, 'Bihar', 'Bettiah', 'India'),
	(254, 'TamilNadu', 'Pollachi', 'India'),
	(255, 'Punjab', 'Khanna', 'India'),
	(256, 'MadhyaPradesh', 'Neemuch', 'India'),
	(257, 'Haryana', 'Palwal', 'India'),
	(258, 'Gujarat', 'Palanpur', 'India'),
	(259, 'AndhraPradesh', 'Guntakal', 'India'),
	(260, 'WestBengal', 'Nabadwip', 'India'),
	(261, 'Karnataka', 'Udupi', 'India'),
	(262, 'Chhattisgarh', 'Jagdalpur', 'India'),
	(263, 'Bihar', 'Motihari', 'India'),
	(264, 'UttarPradesh', 'Pilibhit', 'India'),
	(265, 'Nagaland', 'Dimapur', 'India'),
	(266, 'Punjab', 'Mohali', 'India'),
	(267, 'Rajasthan', 'Sadulpur', 'India'),
	(268, 'TamilNadu', 'Rajapalayam', 'India'),
	(269, 'AndhraPradesh', 'Dharmavaram', 'India'),
	(270, 'Uttarakhand', 'Kashipur', 'India'),
	(271, 'TamilNadu', 'Sivakasi', 'India'),
	(272, 'WestBengal', 'Darjiling', 'India'),
	(273, 'Karnataka', 'Chikkamagaluru', 'India'),
	(274, 'AndhraPradesh', 'Gudivada', 'India'),
	(275, 'Odisha', 'Baleshwar Town', 'India'),
	(276, 'Telangana', 'Mancherial', 'India'),
	(277, 'AndhraPradesh', 'Srikakulam', 'India'),
	(278, 'Telangana', 'Adilabad', 'India'),
	(279, 'Maharashtra', 'Yavatmal', 'India'),
	(280, 'Punjab', 'Barnala', 'India'),
	(281, 'Assam', 'Nagaon', 'India'),
	(282, 'AndhraPradesh', 'Narasaraopet', 'India'),
	(283, 'Chhattisgarh', 'Raigarh', 'India'),
	(284, 'Uttarakhand', 'Roorkee', 'India'),
	(285, 'Gujarat', 'Valsad', 'India'),
	(286, 'Chhattisgarh', 'Ambikapur', 'India'),
	(287, 'Jharkhand', 'Giridih', 'India'),
	(288, 'UttarPradesh', 'Chandausi', 'India'),
	(289, 'WestBengal', 'Purulia', 'India'),
	(290, 'Gujarat', 'Patan', 'India'),
	(291, 'Bihar', 'Bagaha', 'India'),
	(292, 'UttarPradesh', 'Hardoi ', 'India'),
	(293, 'Maharashtra', 'Achalpur', 'India'),
	(294, 'Maharashtra', 'Osmanabad', 'India'),
	(295, 'Gujarat', 'Deesa', 'India'),
	(296, 'Maharashtra', 'Nandurbar', 'India'),
	(297, 'UttarPradesh', 'Azamgarh', 'India'),
	(298, 'Jharkhand', 'Ramgarh', 'India'),
	(299, 'Punjab', 'Firozpur', 'India'),
	(300, 'Odisha', 'Baripada Town', 'India'),
	(301, 'Karnataka', 'Karwar', 'India'),
	(302, 'Bihar', 'Siwan', 'India'),
	(303, 'AndhraPradesh', 'Rajampet', 'India'),
	(304, 'TamilNadu', 'Pudukkottai', 'India'),
	(305, 'JammuandKashmir', 'Anantnag', 'India'),
	(306, 'AndhraPradesh', 'Tadpatri', 'India'),
	(307, 'Maharashtra', 'Satara', 'India'),
	(308, 'Odisha', 'Bhadrak', 'India'),
	(309, 'Bihar', 'Kishanganj', 'India'),
	(310, 'Telangana', 'Suryapet', 'India'),
	(311, 'Maharashtra', 'Wardha', 'India'),
	(312, 'Karnataka', 'Ranebennuru', 'India'),
	(313, 'Gujarat', 'Amreli', 'India'),
	(314, 'TamilNadu', 'Neyveli (TS)', 'India'),
	(315, 'Bihar', 'Jamalpur', 'India'),
	(316, 'Goa', 'Marmagao', 'India'),
	(317, 'Maharashtra', 'Udgir', 'India'),
	(318, 'AndhraPradesh', 'Tadepalligudem', 'India'),
	(319, 'TamilNadu', 'Nagapattinam', 'India'),
	(320, 'Bihar', 'Buxar', 'India'),
	(321, 'Maharashtra', 'Aurangabad', 'India'),
	(322, 'Bihar', 'Jehanabad', 'India'),
	(323, 'Punjab', 'Phagwara', 'India'),
	(324, 'UttarPradesh', 'Khair', 'India'),
	(325, 'Rajasthan', 'Sawai Madhopur', 'India'),
	(326, 'Punjab', 'Kapurthala', 'India'),
	(327, 'AndhraPradesh', 'Chilakaluripet', 'India'),
	(328, 'Bihar', 'Aurangabad', 'India'),
	(329, 'Kerala', 'Malappuram', 'India'),
	(330, 'Haryana', 'Rewari', 'India'),
	(331, 'Rajasthan', 'Nagaur', 'India'),
	(332, 'UttarPradesh', 'Sultanpur', 'India'),
	(333, 'MadhyaPradesh', 'Nagda', 'India'),
	(334, 'AndamanandNicobarIslands', 'Port Blair', 'India'),
	(335, 'Bihar', 'Lakhisarai', 'India'),
	(336, 'Goa', 'Panaji', 'India'),
	(337, 'Assam', 'Tinsukia', 'India'),
	(338, 'MadhyaPradesh', 'Itarsi', 'India'),
	(339, 'Nagaland', 'Kohima', 'India'),
	(340, 'Odisha', 'Balangir', 'India'),
	(341, 'Bihar', 'Nawada', 'India'),
	(342, 'Odisha', 'Jharsuguda', 'India'),
	(343, 'Telangana', 'Jagtial', 'India'),
	(344, 'TamilNadu', 'Viluppuram', 'India'),
	(345, 'Maharashtra', 'Amalner', 'India'),
	(346, 'Punjab', 'Zirakpur', 'India'),
	(347, 'UttarPradesh', 'Tanda', 'India'),
	(348, 'TamilNadu', 'Tiruchengode', 'India'),
	(349, 'UttarPradesh', 'Nagina', 'India'),
	(350, 'AndhraPradesh', 'Yemmiganur', 'India'),
	(351, 'TamilNadu', 'Vaniyambadi', 'India'),
	(352, 'MadhyaPradesh', 'Sarni', 'India'),
	(353, 'TamilNadu', 'Theni Allinagaram', 'India'),
	(354, 'Goa', 'Margao', 'India'),
	(355, 'Maharashtra', 'Akot', 'India'),
	(356, 'MadhyaPradesh', 'Sehore', 'India'),
	(357, 'MadhyaPradesh', 'Mhow Cantonment', 'India'),
	(358, 'Punjab', 'Kot Kapura', 'India'),
	(359, 'Rajasthan', 'Makrana', 'India'),
	(360, 'Maharashtra', 'Pandharpur', 'India'),
	(361, 'Telangana', 'Miryalaguda', 'India'),
	(362, 'UttarPradesh', 'Shamli', 'India'),
	(363, 'MadhyaPradesh', 'Seoni', 'India'),
	(364, 'Karnataka', 'Ranibennur', 'India'),
	(365, 'AndhraPradesh', 'Kadiri', 'India'),
	(366, 'Maharashtra', 'Shrirampur', 'India'),
	(367, 'Uttarakhand', 'Rudrapur', 'India'),
	(368, 'Maharashtra', 'Parli', 'India'),
	(369, 'UttarPradesh', 'Najibabad', 'India'),
	(370, 'Telangana', 'Nirmal', 'India'),
	(371, 'TamilNadu', 'Udhagamandalam', 'India'),
	(372, 'UttarPradesh', 'Shikohabad', 'India'),
	(373, 'Jharkhand', 'Jhumri Tilaiya', 'India'),
	(374, 'TamilNadu', 'Aruppukkottai', 'India'),
	(375, 'Kerala', 'Ponnani', 'India'),
	(376, 'Bihar', 'Jamui', 'India'),
	(377, 'Bihar', 'Sitamarhi', 'India'),
	(378, 'AndhraPradesh', 'Chirala', 'India'),
	(379, 'Gujarat', 'Anjar', 'India'),
	(380, 'Puducherry', 'Karaikal', 'India'),
	(381, 'Haryana', 'Hansi', 'India'),
	(382, 'AndhraPradesh', 'Anakapalle', 'India'),
	(383, 'Chhattisgarh', 'Mahasamund', 'India'),
	(384, 'Punjab', 'Faridkot', 'India'),
	(385, 'Jharkhand', 'Saunda', 'India'),
	(386, 'Gujarat', 'Dhoraji', 'India'),
	(387, 'TamilNadu', 'Paramakudi', 'India'),
	(388, 'MadhyaPradesh', 'Balaghat', 'India'),
	(389, 'Rajasthan', 'Sujangarh', 'India'),
	(390, 'Gujarat', 'Khambhat', 'India'),
	(391, 'Punjab', 'Muktsar', 'India'),
	(392, 'Punjab', 'Rajpura', 'India'),
	(393, 'AndhraPradesh', 'Kavali', 'India'),
	(394, 'Chhattisgarh', 'Dhamtari', 'India'),
	(395, 'MadhyaPradesh', 'Ashok Nagar', 'India'),
	(396, 'Rajasthan', 'Sardarshahar', 'India'),
	(397, 'Gujarat', 'Mahuva', 'India'),
	(398, 'Odisha', 'Bargarh', 'India'),
	(399, 'Telangana', 'Kamareddy', 'India'),
	(400, 'Jharkhand', 'Sahibganj', 'India'),
	(401, 'Telangana', 'Kothagudem', 'India'),
	(402, 'Karnataka', 'Ramanagaram', 'India'),
	(403, 'Karnataka', 'Gokak', 'India'),
	(404, 'MadhyaPradesh', 'Tikamgarh', 'India'),
	(405, 'Bihar', 'Araria', 'India'),
	(406, 'Uttarakhand', 'Rishikesh', 'India'),
	(407, 'MadhyaPradesh', 'Shahdol', 'India'),
	(408, 'Jharkhand', 'Medininagar (Daltonganj)', 'India'),
	(409, 'TamilNadu', 'Arakkonam', 'India'),
	(410, 'Maharashtra', 'Washim', 'India'),
	(411, 'Punjab', 'Sangrur', 'India'),
	(412, 'Telangana', 'Bodhan', 'India'),
	(413, 'Punjab', 'Fazilka', 'India'),
	(414, 'AndhraPradesh', 'Palacole', 'India'),
	(415, 'Gujarat', 'Keshod', 'India'),
	(416, 'AndhraPradesh', 'Sullurpeta', 'India'),
	(417, 'Gujarat', 'Wadhwan', 'India'),
	(418, 'Punjab', 'Gurdaspur', 'India'),
	(419, 'Kerala', 'Vatakara', 'India'),
	(420, 'Meghalaya', 'Tura', 'India'),
	(421, 'Haryana', 'Narnaul', 'India'),
	(422, 'Punjab', 'Kharar', 'India'),
	(423, 'Karnataka', 'Yadgir', 'India'),
	(424, 'Maharashtra', 'Ambejogai', 'India'),
	(425, 'Gujarat', 'Ankleshwar', 'India'),
	(426, 'Gujarat', 'Savarkundla', 'India'),
	(427, 'Odisha', 'Paradip', 'India'),
	(428, 'TamilNadu', 'Virudhachalam', 'India'),
	(429, 'Kerala', 'Kanhangad', 'India'),
	(430, 'Gujarat', 'Kadi', 'India'),
	(431, 'TamilNadu', 'Srivilliputhur', 'India'),
	(432, 'Punjab', 'Gobindgarh', 'India'),
	(433, 'TamilNadu', 'Tindivanam', 'India'),
	(434, 'Punjab', 'Mansa', 'India'),
	(435, 'Kerala', 'Taliparamba', 'India'),
	(436, 'Maharashtra', 'Manmad', 'India'),
	(437, 'AndhraPradesh', 'Tanuku', 'India'),
	(438, 'AndhraPradesh', 'Rayachoti', 'India'),
	(439, 'TamilNadu', 'Virudhunagar', 'India'),
	(440, 'Kerala', 'Koyilandy', 'India'),
	(441, 'Assam', 'Jorhat', 'India'),
	(442, 'TamilNadu', 'Karur', 'India'),
	(443, 'TamilNadu', 'Valparai', 'India'),
	(444, 'AndhraPradesh', 'Srikalahasti', 'India'),
	(445, 'Kerala', 'Neyyattinkara', 'India'),
	(446, 'AndhraPradesh', 'Bapatla', 'India'),
	(447, 'Haryana', 'Fatehabad', 'India'),
	(448, 'Punjab', 'Malout', 'India'),
	(449, 'TamilNadu', 'Sankarankovil', 'India'),
	(450, 'TamilNadu', 'Tenkasi', 'India'),
	(451, 'Maharashtra', 'Ratnagiri', 'India'),
	(452, 'Karnataka', 'Rabkavi Banhatti', 'India'),
	(453, 'UttarPradesh', 'Sikandrabad', 'India'),
	(454, 'Jharkhand', 'Chaibasa', 'India'),
	(455, 'Chhattisgarh', 'Chirmiri', 'India'),
	(456, 'Telangana', 'Palwancha', 'India'),
	(457, 'Odisha', 'Bhawanipatna', 'India'),
	(458, 'Kerala', 'Kayamkulam', 'India'),
	(459, 'MadhyaPradesh', 'Pithampur', 'India'),
	(460, 'Punjab', 'Nabha', 'India'),
	(461, 'UttarPradesh', 'Shahabad, Hardoi', 'India'),
	(462, 'Odisha', 'Dhenkanal', 'India'),
	(463, 'Maharashtra', 'Uran Islampur', 'India'),
	(464, 'Bihar', 'Gopalganj', 'India'),
	(465, 'Assam', 'Bongaigaon City', 'India'),
	(466, 'TamilNadu', 'Palani', 'India'),
	(467, 'Maharashtra', 'Pusad', 'India'),
	(468, 'JammuandKashmir', 'Sopore', 'India'),
	(469, 'UttarPradesh', 'Pilkhuwa', 'India'),
	(470, 'Punjab', 'Tarn Taran', 'India'),
	(471, 'UttarPradesh', 'Renukoot', 'India'),
	(472, 'Telangana', 'Mandamarri', 'India'),
	(473, 'Karnataka', 'Shahabad', 'India'),
	(474, 'Odisha', 'Barbil', 'India'),
	(475, 'Telangana', 'Koratla', 'India'),
	(476, 'Bihar', 'Madhubani', 'India'),
	(477, 'WestBengal', 'Arambagh', 'India'),
	(478, 'Haryana', 'Gohana', 'India'),
	(479, 'Rajasthan', 'Ladnu', 'India'),
	(480, 'TamilNadu', 'Pattukkottai', 'India'),
	(481, 'Karnataka', 'Sirsi', 'India'),
	(482, 'Telangana', 'Sircilla', 'India'),
	(483, 'WestBengal', 'Tamluk', 'India'),
	(484, 'Punjab', 'Jagraon', 'India'),
	(485, 'WestBengal', 'AlipurdUrban Agglomerationr', 'India'),
	(486, 'MadhyaPradesh', 'Alirajpur', 'India'),
	(487, 'Telangana', 'Tandur', 'India'),
	(488, 'AndhraPradesh', 'Naidupet', 'India'),
	(489, 'TamilNadu', 'Tirupathur', 'India'),
	(490, 'Haryana', 'Tohana', 'India'),
	(491, 'Rajasthan', 'Ratangarh', 'India'),
	(492, 'Assam', 'Dhubri', 'India'),
	(493, 'Bihar', 'Masaurhi', 'India'),
	(494, 'Gujarat', 'Visnagar', 'India'),
	(495, 'UttarPradesh', 'Vrindavan', 'India'),
	(496, 'Rajasthan', 'Nokha', 'India'),
	(497, 'AndhraPradesh', 'Nagari', 'India'),
	(498, 'Haryana', 'Narwana', 'India'),
	(499, 'TamilNadu', 'Ramanathapuram', 'India'),
	(500, 'UttarPradesh', 'Ujhani', 'India'),
	(501, 'Bihar', 'Samastipur', 'India'),
	(502, 'UttarPradesh', 'Laharpur', 'India'),
	(503, 'Maharashtra', 'Sangamner', 'India'),
	(504, 'Rajasthan', 'Nimbahera', 'India'),
	(505, 'Telangana', 'Siddipet', 'India'),
	(506, 'WestBengal', 'Suri', 'India'),
	(507, 'Assam', 'Diphu', 'India'),
	(508, 'WestBengal', 'Jhargram', 'India'),
	(509, 'Maharashtra', 'Shirpur-Warwade', 'India'),
	(510, 'UttarPradesh', 'Tilhar', 'India'),
	(511, 'Karnataka', 'Sindhnur', 'India'),
	(512, 'TamilNadu', 'Udumalaipettai', 'India'),
	(513, 'Maharashtra', 'Malkapur', 'India'),
	(514, 'Telangana', 'Wanaparthy', 'India'),
	(515, 'AndhraPradesh', 'Gudur', 'India'),
	(516, 'Odisha', 'Kendujhar', 'India'),
	(517, 'MadhyaPradesh', 'Mandla', 'India'),
	(518, 'HimachalPradesh', 'Mandi', 'India'),
	(519, 'Kerala', 'Nedumangad', 'India'),
	(520, 'Assam', 'North Lakhimpur', 'India'),
	(521, 'AndhraPradesh', 'Vinukonda', 'India'),
	(522, 'Karnataka', 'Tiptur', 'India'),
	(523, 'TamilNadu', 'Gobichettipalayam', 'India'),
	(524, 'Odisha', 'Sunabeda', 'India'),
	(525, 'Maharashtra', 'Wani', 'India'),
	(526, 'Gujarat', 'Upleta', 'India'),
	(527, 'AndhraPradesh', 'Narasapuram', 'India'),
	(528, 'AndhraPradesh', 'Nuzvid', 'India'),
	(529, 'Assam', 'Tezpur', 'India'),
	(530, 'Gujarat', 'Una', 'India'),
	(531, 'AndhraPradesh', 'Markapur', 'India'),
	(532, 'MadhyaPradesh', 'Sheopur', 'India'),
	(533, 'TamilNadu', 'Thiruvarur', 'India'),
	(534, 'Gujarat', 'Sidhpur', 'India'),
	(535, 'UttarPradesh', 'Sahaswan', 'India'),
	(536, 'Rajasthan', 'Suratgarh', 'India'),
	(537, 'MadhyaPradesh', 'Shajapur', 'India'),
	(538, 'Odisha', 'Rayagada', 'India'),
	(539, 'Maharashtra', 'Lonavla', 'India'),
	(540, 'AndhraPradesh', 'Ponnur', 'India'),
	(541, 'Telangana', 'Kagaznagar', 'India'),
	(542, 'Telangana', 'Gadwal', 'India'),
	(543, 'Chhattisgarh', 'Bhatapara', 'India'),
	(544, 'AndhraPradesh', 'Kandukur', 'India'),
	(545, 'Telangana', 'Sangareddy', 'India'),
	(546, 'Gujarat', 'Unjha', 'India'),
	(547, 'Mizoram', 'Lunglei', 'India'),
	(548, 'Assam', 'Karimganj', 'India'),
	(549, 'Kerala', 'Kannur', 'India'),
	(550, 'AndhraPradesh', 'Bobbili', 'India'),
	(551, 'Bihar', 'Mokameh', 'India'),
	(552, 'Maharashtra', 'Talegaon Dabhade', 'India'),
	(553, 'Maharashtra', 'Anjangaon', 'India'),
	(554, 'Gujarat', 'Mangrol', 'India'),
	(555, 'Punjab', 'Sunam', 'India'),
	(556, 'WestBengal', 'Gangarampur', 'India'),
	(557, 'TamilNadu', 'Thiruvallur', 'India'),
	(558, 'Kerala', 'Tirur', 'India'),
	(559, 'UttarPradesh', 'Rath', 'India'),
	(560, 'Odisha', 'Jatani', 'India'),
	(561, 'Gujarat', 'Viramgam', 'India'),
	(562, 'Rajasthan', 'Rajsamand', 'India'),
	(563, 'Puducherry', 'Yanam', 'India'),
	(564, 'Kerala', 'Kottayam', 'India'),
	(565, 'TamilNadu', 'Panruti', 'India'),
	(566, 'Punjab', 'Dhuri', 'India'),
	(567, 'TamilNadu', 'Namakkal', 'India'),
	(568, 'Kerala', 'Kasaragod', 'India'),
	(569, 'Gujarat', 'Modasa', 'India'),
	(570, 'AndhraPradesh', 'Rayadurg', 'India'),
	(571, 'Bihar', 'Supaul', 'India'),
	(572, 'Kerala', 'Kunnamkulam', 'India'),
	(573, 'Maharashtra', 'Umred', 'India'),
	(574, 'Telangana', 'Bellampalle', 'India'),
	(575, 'Assam', 'Sibsagar', 'India'),
	(576, 'Haryana', 'Mandi Dabwali', 'India'),
	(577, 'Kerala', 'Ottappalam', 'India'),
	(578, 'Bihar', 'Dumraon', 'India'),
	(579, 'AndhraPradesh', 'Samalkot', 'India'),
	(580, 'AndhraPradesh', 'Jaggaiahpet', 'India'),
	(581, 'Assam', 'Goalpara', 'India'),
	(582, 'AndhraPradesh', 'Tuni', 'India'),
	(583, 'Rajasthan', 'Lachhmangarh', 'India'),
	(584, 'Telangana', 'Bhongir', 'India'),
	(585, 'AndhraPradesh', 'Amalapuram', 'India'),
	(586, 'Punjab', 'Firozpur Cantt.', 'India'),
	(587, 'Telangana', 'Vikarabad', 'India'),
	(588, 'Kerala', 'Thiruvalla', 'India'),
	(589, 'UttarPradesh', 'Sherkot', 'India'),
	(590, 'Maharashtra', 'Palghar', 'India'),
	(591, 'Maharashtra', 'Shegaon', 'India'),
	(592, 'Telangana', 'Jangaon', 'India'),
	(593, 'AndhraPradesh', 'Bheemunipatnam', 'India'),
	(594, 'MadhyaPradesh', 'Panna', 'India'),
	(595, 'Kerala', 'Thodupuzha', 'India'),
	(596, 'JammuandKashmir', 'KathUrban Agglomeration', 'India'),
	(597, 'Gujarat', 'Palitana', 'India'),
	(598, 'Bihar', 'Arwal', 'India'),
	(599, 'AndhraPradesh', 'Venkatagiri', 'India'),
	(600, 'UttarPradesh', 'Kalpi', 'India'),
	(601, 'Rajasthan', 'Rajgarh (Churu)', 'India'),
	(602, 'AndhraPradesh', 'Sattenapalle', 'India'),
	(603, 'Karnataka', 'Arsikere', 'India'),
	(604, 'Maharashtra', 'Ozar', 'India'),
	(605, 'TamilNadu', 'Thirumangalam', 'India'),
	(606, 'Gujarat', 'Petlad', 'India'),
	(607, 'Rajasthan', 'Nasirabad', 'India'),
	(608, 'Maharashtra', 'Phaltan', 'India'),
	(609, 'WestBengal', 'Rampurhat', 'India'),
	(610, 'Karnataka', 'Nanjangud', 'India'),
	(611, 'Bihar', 'Forbesganj', 'India'),
	(612, 'UttarPradesh', 'Tundla', 'India'),
	(613, 'Bihar', 'BhabUrban Agglomeration', 'India'),
	(614, 'Karnataka', 'Sagara', 'India'),
	(615, 'AndhraPradesh', 'Pithapuram', 'India'),
	(616, 'Karnataka', 'Sira', 'India'),
	(617, 'Telangana', 'Bhadrachalam', 'India'),
	(618, 'Haryana', 'Charkhi Dadri', 'India'),
	(619, 'Jharkhand', 'Chatra', 'India'),
	(620, 'AndhraPradesh', 'Palasa Kasibugga', 'India'),
	(621, 'Rajasthan', 'Nohar', 'India'),
	(622, 'Maharashtra', 'Yevla', 'India'),
	(623, 'Punjab', 'Sirhind Fatehgarh Sahib', 'India'),
	(624, 'Telangana', 'Bhainsa', 'India'),
	(625, 'AndhraPradesh', 'Parvathipuram', 'India'),
	(626, 'Maharashtra', 'Shahade', 'India'),
	(627, 'Kerala', 'Chalakudy', 'India'),
	(628, 'Bihar', 'Narkatiaganj', 'India'),
	(629, 'Gujarat', 'Kapadvanj', 'India'),
	(630, 'AndhraPradesh', 'Macherla', 'India'),
	(631, 'MadhyaPradesh', 'Raghogarh-Vijaypur', 'India'),
	(632, 'Punjab', 'Rupnagar', 'India'),
	(633, 'Bihar', 'Naugachhia', 'India'),
	(634, 'MadhyaPradesh', 'Sendhwa', 'India'),
	(635, 'Odisha', 'Byasanagar', 'India'),
	(636, 'UttarPradesh', 'Sandila', 'India'),
	(637, 'AndhraPradesh', 'Gooty', 'India'),
	(638, 'AndhraPradesh', 'Salur', 'India'),
	(639, 'UttarPradesh', 'Nanpara', 'India'),
	(640, 'UttarPradesh', 'Sardhana', 'India'),
	(641, 'Maharashtra', 'Vita', 'India'),
	(642, 'Jharkhand', 'Gumia', 'India'),
	(643, 'Karnataka', 'Puttur', 'India'),
	(644, 'Punjab', 'Jalandhar Cantt.', 'India'),
	(645, 'UttarPradesh', 'Nehtaur', 'India'),
	(646, 'Kerala', 'Changanassery', 'India'),
	(647, 'AndhraPradesh', 'Mandapeta', 'India'),
	(648, 'Jharkhand', 'Dumka', 'India'),
	(649, 'UttarPradesh', 'Seohara', 'India'),
	(650, 'Maharashtra', 'Umarkhed', 'India'),
	(651, 'Jharkhand', 'Madhupur', 'India'),
	(652, 'TamilNadu', 'Vikramasingapuram', 'India'),
	(653, 'Kerala', 'Punalur', 'India'),
	(654, 'Odisha', 'Kendrapara', 'India'),
	(655, 'Gujarat', 'Sihor', 'India'),
	(656, 'TamilNadu', 'Nellikuppam', 'India'),
	(657, 'Punjab', 'Samana', 'India'),
	(658, 'Maharashtra', 'Warora', 'India'),
	(659, 'Kerala', 'Nilambur', 'India'),
	(660, 'TamilNadu', 'Rasipuram', 'India'),
	(661, 'Uttarakhand', 'Ramnagar', 'India'),
	(662, 'AndhraPradesh', 'Jammalamadugu', 'India'),
	(663, 'Punjab', 'Nawanshahr', 'India'),
	(664, 'Manipur', 'Thoubal', 'India'),
	(665, 'Karnataka', 'Athni', 'India'),
	(666, 'Kerala', 'Cherthala', 'India'),
	(667, 'MadhyaPradesh', 'Sidhi', 'India'),
	(668, 'Telangana', 'Farooqnagar', 'India'),
	(669, 'AndhraPradesh', 'Peddapuram', 'India'),
	(670, 'Jharkhand', 'Chirkunda', 'India'),
	(671, 'Maharashtra', 'Pachora', 'India'),
	(672, 'Bihar', 'Madhepura', 'India'),
	(673, 'Uttarakhand', 'Pithoragarh', 'India'),
	(674, 'Maharashtra', 'Tumsar', 'India'),
	(675, 'Rajasthan', 'Phalodi', 'India'),
	(676, 'TamilNadu', 'Tiruttani', 'India'),
	(677, 'Punjab', 'Rampura Phul', 'India'),
	(678, 'Kerala', 'Perinthalmanna', 'India'),
	(679, 'UttarPradesh', 'Padrauna', 'India'),
	(680, 'MadhyaPradesh', 'Pipariya', 'India'),
	(681, 'Chhattisgarh', 'Dalli-Rajhara', 'India'),
	(682, 'AndhraPradesh', 'Punganur', 'India'),
	(683, 'Kerala', 'Mattannur', 'India'),
	(684, 'UttarPradesh', 'Mathura', 'India'),
	(685, 'UttarPradesh', 'Thakurdwara', 'India'),
	(686, 'TamilNadu', 'Nandivaram-Guduvancheri', 'India'),
	(687, 'Karnataka', 'Mulbagal', 'India'),
	(688, 'Maharashtra', 'Manjlegaon', 'India'),
	(689, 'Gujarat', 'Wankaner', 'India'),
	(690, 'Maharashtra', 'Sillod', 'India'),
	(691, 'AndhraPradesh', 'Nidadavole', 'India'),
	(692, 'Karnataka', 'Surapura', 'India'),
	(693, 'Odisha', 'Rajagangapur', 'India'),
	(694, 'Bihar', 'Sheikhpura', 'India'),
	(695, 'Odisha', 'Parlakhemundi', 'India'),
	(696, 'WestBengal', 'Kalimpong', 'India'),
	(697, 'Karnataka', 'Siruguppa', 'India'),
	(698, 'Maharashtra', 'Arvi', 'India'),
	(699, 'Gujarat', 'Limbdi', 'India'),
	(700, 'Assam', 'Barpeta', 'India'),
	(701, 'Uttarakhand', 'Manglaur', 'India'),
	(702, 'AndhraPradesh', 'Repalle', 'India'),
	(703, 'Karnataka', 'Mudhol', 'India'),
	(704, 'MadhyaPradesh', 'Shujalpur', 'India'),
	(705, 'Gujarat', 'Mandvi', 'India'),
	(706, 'Gujarat', 'Thangadh', 'India'),
	(707, 'MadhyaPradesh', 'Sironj', 'India'),
	(708, 'Maharashtra', 'Nandura', 'India'),
	(709, 'Kerala', 'Shoranur', 'India'),
	(710, 'Rajasthan', 'Nathdwara', 'India'),
	(711, 'TamilNadu', 'Periyakulam', 'India'),
	(712, 'Bihar', 'Sultanganj', 'India'),
	(713, 'Telangana', 'Medak', 'India'),
	(714, 'Telangana', 'Narayanpet', 'India'),
	(715, 'Bihar', 'Raxaul Bazar', 'India'),
	(716, 'JammuandKashmir', 'Rajauri', 'India'),
	(717, 'TamilNadu', 'Pernampattu', 'India'),
	(718, 'Uttarakhand', 'Nainital', 'India'),
	(719, 'AndhraPradesh', 'Ramachandrapuram', 'India'),
	(720, 'Maharashtra', 'Vaijapur', 'India'),
	(721, 'Punjab', 'Nangal', 'India'),
	(722, 'Karnataka', 'Sidlaghatta', 'India'),
	(723, 'JammuandKashmir', 'Punch', 'India'),
	(724, 'MadhyaPradesh', 'Pandhurna', 'India'),
	(725, 'Maharashtra', 'Wadgaon Road', 'India'),
	(726, 'Odisha', 'Talcher', 'India'),
	(727, 'Kerala', 'Varkala', 'India'),
	(728, 'Rajasthan', 'Pilani', 'India'),
	(729, 'MadhyaPradesh', 'Nowgong', 'India'),
	(730, 'Chhattisgarh', 'Naila Janjgir', 'India'),
	(731, 'Goa', 'Mapusa', 'India'),
	(732, 'TamilNadu', 'Vellakoil', 'India'),
	(733, 'Rajasthan', 'Merta City', 'India'),
	(734, 'TamilNadu', 'Sivaganga', 'India'),
	(735, 'MadhyaPradesh', 'Mandideep', 'India'),
	(736, 'Maharashtra', 'Sailu', 'India'),
	(737, 'Gujarat', 'Vyara', 'India'),
	(738, 'AndhraPradesh', 'Kovvur', 'India'),
	(739, 'TamilNadu', 'Vadalur', 'India'),
	(740, 'UttarPradesh', 'Nawabganj', 'India'),
	(741, 'Gujarat', 'Padra', 'India'),
	(742, 'WestBengal', 'Sainthia', 'India'),
	(743, 'UttarPradesh', 'Siana', 'India'),
	(744, 'Karnataka', 'Shahpur', 'India'),
	(745, 'Rajasthan', 'Sojat', 'India'),
	(746, 'UttarPradesh', 'Noorpur', 'India'),
	(747, 'Kerala', 'Paravoor', 'India'),
	(748, 'Maharashtra', 'Murtijapur', 'India'),
	(749, 'Bihar', 'Ramnagar', 'India'),
	(750, 'Odisha', 'Sundargarh', 'India'),
	(751, 'WestBengal', 'Taki', 'India'),
	(752, 'Karnataka', 'Saundatti-Yellamma', 'India'),
	(753, 'Kerala', 'Pathanamthitta', 'India'),
	(754, 'Karnataka', 'Wadi', 'India'),
	(755, 'TamilNadu', 'Rameshwaram', 'India'),
	(756, 'Maharashtra', 'Tasgaon', 'India'),
	(757, 'UttarPradesh', 'Sikandra Rao', 'India'),
	(758, 'MadhyaPradesh', 'Sihora', 'India'),
	(759, 'TamilNadu', 'Tiruvethipuram', 'India'),
	(760, 'AndhraPradesh', 'Tiruvuru', 'India'),
	(761, 'Maharashtra', 'Mehkar', 'India'),
	(762, 'Kerala', 'Peringathur', 'India'),
	(763, 'TamilNadu', 'Perambalur', 'India'),
	(764, 'Karnataka', 'Manvi', 'India'),
	(765, 'Nagaland', 'Zunheboto', 'India'),
	(766, 'Bihar', 'Mahnar Bazar', 'India'),
	(767, 'Kerala', 'Attingal', 'India'),
	(768, 'Haryana', 'Shahbad', 'India'),
	(769, 'UttarPradesh', 'Puranpur', 'India'),
	(770, 'Karnataka', 'Nelamangala', 'India'),
	(771, 'Punjab', 'Nakodar', 'India'),
	(772, 'Gujarat', 'Lunawada', 'India'),
	(773, 'WestBengal', 'Murshidabad', 'India'),
	(774, 'Puducherry', 'Mahe', 'India'),
	(775, 'Assam', 'Lanka', 'India'),
	(776, 'UttarPradesh', 'Rudauli', 'India'),
	(777, 'Nagaland', 'Tuensang', 'India'),
	(778, 'Karnataka', 'Lakshmeshwar', 'India'),
	(779, 'Punjab', 'Zira', 'India'),
	(780, 'Maharashtra', 'Yawal', 'India'),
	(781, 'UttarPradesh', 'Thana Bhawan', 'India'),
	(782, 'Karnataka', 'Ramdurg', 'India'),
	(783, 'Maharashtra', 'Pulgaon', 'India'),
	(784, 'Telangana', 'Sadasivpet', 'India'),
	(785, 'Karnataka', 'Nargund', 'India'),
	(786, 'Rajasthan', 'Neem-Ka-Thana', 'India'),
	(787, 'WestBengal', 'Memari', 'India'),
	(788, 'Maharashtra', 'Nilanga', 'India'),
	(789, 'ArunachalPradesh', 'Naharlagun', 'India'),
	(790, 'Jharkhand', 'Pakaur', 'India'),
	(791, 'Maharashtra', 'Wai', 'India'),
	(792, 'Karnataka', 'Tarikere', 'India'),
	(793, 'Karnataka', 'Malavalli', 'India'),
	(794, 'MadhyaPradesh', 'Raisen', 'India'),
	(795, 'MadhyaPradesh', 'Lahar', 'India'),
	(796, 'AndhraPradesh', 'Uravakonda', 'India'),
	(797, 'Karnataka', 'Savanur', 'India'),
	(798, 'Rajasthan', 'Sirohi', 'India'),
	(799, 'JammuandKashmir', 'Udhampur', 'India'),
	(800, 'Maharashtra', 'Umarga', 'India'),
	(801, 'Rajasthan', 'Pratapgarh', 'India'),
	(802, 'Karnataka', 'Lingsugur', 'India'),
	(803, 'TamilNadu', 'Usilampatti', 'India'),
	(804, 'UttarPradesh', 'Palia Kalan', 'India'),
	(805, 'Nagaland', 'Wokha', 'India'),
	(806, 'Gujarat', 'Rajpipla', 'India'),
	(807, 'Karnataka', 'Vijayapura', 'India'),
	(808, 'Rajasthan', 'Rawatbhata', 'India'),
	(809, 'Rajasthan', 'Sangaria', 'India'),
	(810, 'Maharashtra', 'Paithan', 'India'),
	(811, 'Maharashtra', 'Rahuri', 'India'),
	(812, 'Punjab', 'Patti', 'India'),
	(813, 'UttarPradesh', 'Zaidpur', 'India'),
	(814, 'Rajasthan', 'Lalsot', 'India'),
	(815, 'MadhyaPradesh', 'Maihar', 'India'),
	(816, 'TamilNadu', 'Vedaranyam', 'India'),
	(817, 'Maharashtra', 'Nawapur', 'India'),
	(818, 'HimachalPradesh', 'Solan', 'India'),
	(819, 'Gujarat', 'Vapi', 'India'),
	(820, 'MadhyaPradesh', 'Sanawad', 'India'),
	(821, 'Bihar', 'Warisaliganj', 'India'),
	(822, 'Bihar', 'Revelganj', 'India'),
	(823, 'MadhyaPradesh', 'Sabalgarh', 'India'),
	(824, 'Maharashtra', 'Tuljapur', 'India'),
	(825, 'Jharkhand', 'Simdega', 'India'),
	(826, 'Jharkhand', 'Musabani', 'India'),
	(827, 'Kerala', 'Kodungallur', 'India'),
	(828, 'Odisha', 'Phulabani', 'India'),
	(829, 'Gujarat', 'Umreth', 'India'),
	(830, 'AndhraPradesh', 'Narsipatnam', 'India'),
	(831, 'UttarPradesh', 'Nautanwa', 'India'),
	(832, 'Bihar', 'Rajgir', 'India'),
	(833, 'Telangana', 'Yellandu', 'India'),
	(834, 'TamilNadu', 'Sathyamangalam', 'India'),
	(835, 'Rajasthan', 'Pilibanga', 'India'),
	(836, 'Maharashtra', 'Morshi', 'India'),
	(837, 'Haryana', 'Pehowa', 'India'),
	(838, 'Bihar', 'Sonepur', 'India'),
	(839, 'Kerala', 'Pappinisseri', 'India'),
	(840, 'UttarPradesh', 'Zamania', 'India'),
	(841, 'Jharkhand', 'Mihijam', 'India'),
	(842, 'Maharashtra', 'Purna', 'India'),
	(843, 'TamilNadu', 'Puliyankudi', 'India'),
	(844, 'UttarPradesh', 'Shikarpur, Bulandshahr', 'India'),
	(845, 'MadhyaPradesh', 'Umaria', 'India'),
	(846, 'MadhyaPradesh', 'Porsa', 'India'),
	(847, 'UttarPradesh', 'Naugawan Sadat', 'India'),
	(848, 'UttarPradesh', 'Fatehpur Sikri', 'India'),
	(849, 'Telangana', 'Manuguru', 'India'),
	(850, 'Tripura', 'Udaipur', 'India'),
	(851, 'Rajasthan', 'Pipar City', 'India'),
	(852, 'Odisha', 'Pattamundai', 'India'),
	(853, 'TamilNadu', 'Nanjikottai', 'India'),
	(854, 'Rajasthan', 'Taranagar', 'India'),
	(855, 'AndhraPradesh', 'Yerraguntla', 'India'),
	(856, 'Maharashtra', 'Satana', 'India'),
	(857, 'Bihar', 'Sherghati', 'India'),
	(858, 'Karnataka', 'Sankeshwara', 'India'),
	(859, 'Karnataka', 'Madikeri', 'India'),
	(860, 'TamilNadu', 'Thuraiyur', 'India'),
	(861, 'Gujarat', 'Sanand', 'India'),
	(862, 'Gujarat', 'Rajula', 'India'),
	(863, 'Telangana', 'Kyathampalle', 'India'),
	(864, 'UttarPradesh', 'Shahabad, Rampur', 'India'),
	(865, 'Chhattisgarh', 'Tilda Newra', 'India'),
	(866, 'MadhyaPradesh', 'Narsinghgarh', 'India'),
	(867, 'Kerala', 'Chittur-Thathamangalam', 'India'),
	(868, 'MadhyaPradesh', 'Malaj Khand', 'India'),
	(869, 'MadhyaPradesh', 'Sarangpur', 'India'),
	(870, 'UttarPradesh', 'Robertsganj', 'India'),
	(871, 'TamilNadu', 'Sirkali', 'India'),
	(872, 'Gujarat', 'Radhanpur', 'India'),
	(873, 'TamilNadu', 'Tiruchendur', 'India'),
	(874, 'UttarPradesh', 'Utraula', 'India'),
	(875, 'Jharkhand', 'Patratu', 'India'),
	(876, 'Rajasthan', 'Vijainagar, Ajmer', 'India'),
	(877, 'TamilNadu', 'Periyasemur', 'India'),
	(878, 'Maharashtra', 'Pathri', 'India'),
	(879, 'UttarPradesh', 'Sadabad', 'India'),
	(880, 'Karnataka', 'Talikota', 'India'),
	(881, 'Maharashtra', 'Sinnar', 'India'),
	(882, 'Chhattisgarh', 'Mungeli', 'India'),
	(883, 'Karnataka', 'Sedam', 'India'),
	(884, 'Karnataka', 'Shikaripur', 'India'),
	(885, 'Rajasthan', 'Sumerpur', 'India'),
	(886, 'TamilNadu', 'Sattur', 'India'),
	(887, 'Bihar', 'Sugauli', 'India'),
	(888, 'Assam', 'Lumding', 'India'),
	(889, 'TamilNadu', 'Vandavasi', 'India'),
	(890, 'Odisha', 'Titlagarh', 'India'),
	(891, 'Maharashtra', 'Uchgaon', 'India'),
	(892, 'Nagaland', 'Mokokchung', 'India'),
	(893, 'WestBengal', 'Paschim Punropara', 'India'),
	(894, 'Rajasthan', 'Sagwara', 'India'),
	(895, 'Rajasthan', 'Ramganj Mandi', 'India'),
	(896, 'WestBengal', 'Tarakeswar', 'India'),
	(897, 'Karnataka', 'Mahalingapura', 'India'),
	(898, 'Tripura', 'Dharmanagar', 'India'),
	(899, 'Gujarat', 'Mahemdabad', 'India'),
	(900, 'Chhattisgarh', 'Manendragarh', 'India'),
	(901, 'Maharashtra', 'Uran', 'India'),
	(902, 'TamilNadu', 'Tharamangalam', 'India'),
	(903, 'TamilNadu', 'Tirukkoyilur', 'India'),
	(904, 'Maharashtra', 'Pen', 'India'),
	(905, 'Bihar', 'Makhdumpur', 'India'),
	(906, 'Bihar', 'Maner', 'India'),
	(907, 'TamilNadu', 'Oddanchatram', 'India'),
	(908, 'TamilNadu', 'Palladam', 'India'),
	(909, 'MadhyaPradesh', 'Mundi', 'India'),
	(910, 'Odisha', 'Nabarangapur', 'India'),
	(911, 'Karnataka', 'Mudalagi', 'India'),
	(912, 'Haryana', 'Samalkha', 'India'),
	(913, 'MadhyaPradesh', 'Nepanagar', 'India'),
	(914, 'Maharashtra', 'Karjat', 'India'),
	(915, 'Gujarat', 'Ranavav', 'India'),
	(916, 'AndhraPradesh', 'Pedana', 'India'),
	(917, 'Haryana', 'Pinjore', 'India'),
	(918, 'Rajasthan', 'Lakheri', 'India'),
	(919, 'MadhyaPradesh', 'Pasan', 'India'),
	(920, 'AndhraPradesh', 'Puttur', 'India'),
	(921, 'TamilNadu', 'Vadakkuvalliyur', 'India'),
	(922, 'TamilNadu', 'Tirukalukundram', 'India'),
	(923, 'MadhyaPradesh', 'Mahidpur', 'India'),
	(924, 'Uttarakhand', 'Mussoorie', 'India'),
	(925, 'Kerala', 'Muvattupuzha', 'India'),
	(926, 'UttarPradesh', 'Rasra', 'India'),
	(927, 'Rajasthan', 'Udaipurwati', 'India'),
	(928, 'Maharashtra', 'Manwath', 'India'),
	(929, 'Kerala', 'Adoor', 'India'),
	(930, 'TamilNadu', 'Uthamapalayam', 'India'),
	(931, 'Maharashtra', 'Partur', 'India'),
	(932, 'HimachalPradesh', 'Nahan', 'India'),
	(933, 'Haryana', 'Ladwa', 'India'),
	(934, 'Assam', 'Mankachar', 'India'),
	(935, 'Meghalaya', 'Nongstoin', 'India'),
	(936, 'Rajasthan', 'Losal', 'India'),
	(937, 'Rajasthan', 'Sri Madhopur', 'India'),
	(938, 'Rajasthan', 'Ramngarh', 'India'),
	(939, 'Kerala', 'Mavelikkara', 'India'),
	(940, 'Rajasthan', 'Rawatsar', 'India'),
	(941, 'Rajasthan', 'Rajakhera', 'India'),
	(942, 'UttarPradesh', 'Lar', 'India'),
	(943, 'UttarPradesh', 'Lal Gopalganj Nindaura', 'India'),
	(944, 'Karnataka', 'Muddebihal', 'India'),
	(945, 'UttarPradesh', 'Sirsaganj', 'India'),
	(946, 'Rajasthan', 'Shahpura', 'India'),
	(947, 'TamilNadu', 'Surandai', 'India'),
	(948, 'Maharashtra', 'Sangole', 'India'),
	(949, 'Karnataka', 'Pavagada', 'India'),
	(950, 'Gujarat', 'Tharad', 'India'),
	(951, 'Gujarat', 'Mansa', 'India'),
	(952, 'Gujarat', 'Umbergaon', 'India'),
	(953, 'Kerala', 'Mavoor', 'India'),
	(954, 'Assam', 'Nalbari', 'India'),
	(955, 'Gujarat', 'Talaja', 'India'),
	(956, 'Karnataka', 'Malur', 'India'),
	(957, 'Maharashtra', 'Mangrulpir', 'India'),
	(958, 'Odisha', 'Soro', 'India'),
	(959, 'Rajasthan', 'Shahpura', 'India'),
	(960, 'Gujarat', 'Vadnagar', 'India'),
	(961, 'Rajasthan', 'Raisinghnagar', 'India'),
	(962, 'Karnataka', 'Sindhagi', 'India'),
	(963, 'Karnataka', 'Sanduru', 'India'),
	(964, 'Haryana', 'Sohna', 'India'),
	(965, 'Gujarat', 'Manavadar', 'India'),
	(966, 'UttarPradesh', 'Pihani', 'India'),
	(967, 'Haryana', 'Safidon', 'India'),
	(968, 'Maharashtra', 'Risod', 'India'),
	(969, 'Bihar', 'Rosera', 'India'),
	(970, 'TamilNadu', 'Sankari', 'India'),
	(971, 'Rajasthan', 'Malpura', 'India'),
	(972, 'WestBengal', 'Sonamukhi', 'India'),
	(973, 'UttarPradesh', 'Shamsabad, Agra', 'India'),
	(974, 'Bihar', 'Nokha', 'India'),
	(975, 'WestBengal', 'PandUrban Agglomeration', 'India'),
	(976, 'WestBengal', 'Mainaguri', 'India'),
	(977, 'Karnataka', 'Afzalpur', 'India'),
	(978, 'Maharashtra', 'Shirur', 'India'),
	(979, 'Gujarat', 'Salaya', 'India'),
	(980, 'TamilNadu', 'Shenkottai', 'India'),
	(981, 'Tripura', 'Pratapgarh', 'India'),
	(982, 'TamilNadu', 'Vadipatti', 'India'),
	(983, 'Telangana', 'Nagarkurnool', 'India'),
	(984, 'Maharashtra', 'Savner', 'India'),
	(985, 'Maharashtra', 'Sasvad', 'India'),
	(986, 'UttarPradesh', 'Rudrapur', 'India'),
	(987, 'UttarPradesh', 'Soron', 'India'),
	(988, 'TamilNadu', 'Sholingur', 'India'),
	(989, 'Maharashtra', 'Pandharkaoda', 'India'),
	(990, 'Kerala', 'Perumbavoor', 'India'),
	(991, 'Karnataka', 'Maddur', 'India'),
	(992, 'Rajasthan', 'Nadbai', 'India'),
	(993, 'Maharashtra', 'Talode', 'India'),
	(994, 'Maharashtra', 'Shrigonda', 'India'),
	(995, 'Karnataka', 'Madhugiri', 'India'),
	(996, 'Karnataka', 'Tekkalakote', 'India'),
	(997, 'MadhyaPradesh', 'Seoni-Malwa', 'India'),
	(998, 'Maharashtra', 'Shirdi', 'India'),
	(999, 'UttarPradesh', 'SUrban Agglomerationr', 'India'),
	(1000, 'Karnataka', 'Terdal', 'India'),
	(1001, 'Maharashtra', 'Raver', 'India'),
	(1002, 'TamilNadu', 'Tirupathur', 'India'),
	(1003, 'Haryana', 'Taraori', 'India'),
	(1004, 'Maharashtra', 'Mukhed', 'India'),
	(1005, 'TamilNadu', 'Manachanallur', 'India'),
	(1006, 'MadhyaPradesh', 'Rehli', 'India'),
	(1007, 'Rajasthan', 'Sanchore', 'India'),
	(1008, 'Maharashtra', 'Rajura', 'India'),
	(1009, 'Bihar', 'Piro', 'India'),
	(1010, 'Karnataka', 'Mudabidri', 'India'),
	(1011, 'Maharashtra', 'Vadgaon Kasba', 'India'),
	(1012, 'Rajasthan', 'Nagar', 'India'),
	(1013, 'Gujarat', 'Vijapur', 'India'),
	(1014, 'TamilNadu', 'Viswanatham', 'India'),
	(1015, 'TamilNadu', 'Polur', 'India'),
	(1016, 'TamilNadu', 'Panagudi', 'India'),
	(1017, 'MadhyaPradesh', 'Manawar', 'India'),
	(1018, 'Uttarakhand', 'Tehri', 'India'),
	(1019, 'UttarPradesh', 'Samdhan', 'India'),
	(1020, 'Gujarat', 'Pardi', 'India'),
	(1021, 'MadhyaPradesh', 'Rahatgarh', 'India'),
	(1022, 'MadhyaPradesh', 'Panagar', 'India'),
	(1023, 'TamilNadu', 'Uthiramerur', 'India'),
	(1024, 'Maharashtra', 'Tirora', 'India'),
	(1025, 'Assam', 'Rangia', 'India'),
	(1026, 'UttarPradesh', 'Sahjanwa', 'India'),
	(1027, 'MadhyaPradesh', 'Wara Seoni', 'India'),
	(1028, 'Karnataka', 'Magadi', 'India'),
	(1029, 'Rajasthan', 'Rajgarh (Alwar)', 'India'),
	(1030, 'Bihar', 'Rafiganj', 'India'),
	(1031, 'MadhyaPradesh', 'Tarana', 'India'),
	(1032, 'UttarPradesh', 'Rampur Maniharan', 'India'),
	(1033, 'Rajasthan', 'Sheoganj', 'India'),
	(1034, 'Punjab', 'Raikot', 'India'),
	(1035, 'Uttarakhand', 'Pauri', 'India'),
	(1036, 'UttarPradesh', 'Sumerpur', 'India'),
	(1037, 'Karnataka', 'Navalgund', 'India'),
	(1038, 'UttarPradesh', 'Shahganj', 'India'),
	(1039, 'Bihar', 'Marhaura', 'India'),
	(1040, 'UttarPradesh', 'Tulsipur', 'India'),
	(1041, 'Rajasthan', 'Sadri', 'India'),
	(1042, 'TamilNadu', 'Thiruthuraipoondi', 'India'),
	(1043, 'Karnataka', 'Shiggaon', 'India'),
	(1044, 'TamilNadu', 'Pallapatti', 'India'),
	(1045, 'Haryana', 'Mahendragarh', 'India'),
	(1046, 'MadhyaPradesh', 'Sausar', 'India'),
	(1047, 'TamilNadu', 'Ponneri', 'India'),
	(1048, 'Maharashtra', 'Mahad', 'India'),
	(1049, 'Jharkhand', 'Lohardaga', 'India'),
	(1050, 'UttarPradesh', 'Tirwaganj', 'India'),
	(1051, 'Assam', 'Margherita', 'India'),
	(1052, 'HimachalPradesh', 'Sundarnagar', 'India'),
	(1053, 'MadhyaPradesh', 'Rajgarh', 'India'),
	(1054, 'Assam', 'Mangaldoi', 'India'),
	(1055, 'AndhraPradesh', 'Renigunta', 'India'),
	(1056, 'Punjab', 'Longowal', 'India'),
	(1057, 'Haryana', 'Ratia', 'India'),
	(1058, 'TamilNadu', 'Lalgudi', 'India'),
	(1059, 'Karnataka', 'Shrirangapattana', 'India'),
	(1060, 'MadhyaPradesh', 'Niwari', 'India'),
	(1061, 'TamilNadu', 'Natham', 'India'),
	(1062, 'TamilNadu', 'Unnamalaikadai', 'India'),
	(1063, 'UttarPradesh', 'PurqUrban Agglomerationzi', 'India'),
	(1064, 'UttarPradesh', 'Shamsabad, Farrukhabad', 'India'),
	(1065, 'Bihar', 'Mirganj', 'India'),
	(1066, 'Rajasthan', 'Todaraisingh', 'India'),
	(1067, 'UttarPradesh', 'Warhapur', 'India'),
	(1068, 'AndhraPradesh', 'Rajam', 'India'),
	(1069, 'Punjab', 'Urmar Tanda', 'India'),
	(1070, 'Maharashtra', 'Lonar', 'India'),
	(1071, 'UttarPradesh', 'Powayan', 'India'),
	(1072, 'TamilNadu', 'P.N.Patti', 'India'),
	(1073, 'HimachalPradesh', 'Palampur', 'India'),
	(1074, 'AndhraPradesh', 'Srisailam Project (Right Flank Colony) Township', 'India'),
	(1075, 'Karnataka', 'Sindagi', 'India'),
	(1076, 'UttarPradesh', 'Sandi', 'India'),
	(1077, 'Kerala', 'Vaikom', 'India'),
	(1078, 'WestBengal', 'Malda', 'India'),
	(1079, 'TamilNadu', 'Tharangambadi', 'India'),
	(1080, 'Karnataka', 'Sakaleshapura', 'India'),
	(1081, 'Bihar', 'Lalganj', 'India'),
	(1082, 'Odisha', 'Malkangiri', 'India'),
	(1083, 'Gujarat', 'Rapar', 'India'),
	(1084, 'MadhyaPradesh', 'Mauganj', 'India'),
	(1085, 'Rajasthan', 'Todabhim', 'India'),
	(1086, 'Karnataka', 'Srinivaspur', 'India'),
	(1087, 'Bihar', 'Murliganj', 'India'),
	(1088, 'Rajasthan', 'Reengus', 'India'),
	(1089, 'Maharashtra', 'Sawantwadi', 'India'),
	(1090, 'TamilNadu', 'Tittakudi', 'India'),
	(1091, 'Manipur', 'Lilong', 'India'),
	(1092, 'Rajasthan', 'Rajaldesar', 'India'),
	(1093, 'Maharashtra', 'Pathardi', 'India'),
	(1094, 'UttarPradesh', 'Achhnera', 'India'),
	(1095, 'TamilNadu', 'Pacode', 'India'),
	(1096, 'UttarPradesh', 'Naraura', 'India'),
	(1097, 'UttarPradesh', 'Nakur', 'India'),
	(1098, 'Kerala', 'Palai', 'India'),
	(1099, 'Punjab', 'Morinda, India', 'India'),
	(1100, 'MadhyaPradesh', 'Manasa', 'India'),
	(1101, 'MadhyaPradesh', 'Nainpur', 'India'),
	(1102, 'UttarPradesh', 'Sahaspur', 'India'),
	(1103, 'Maharashtra', 'Pauni', 'India'),
	(1104, 'MadhyaPradesh', 'Prithvipur', 'India'),
	(1105, 'Maharashtra', 'Ramtek', 'India'),
	(1106, 'Assam', 'Silapathar', 'India'),
	(1107, 'Gujarat', 'Songadh', 'India'),
	(1108, 'UttarPradesh', 'Safipur', 'India'),
	(1109, 'MadhyaPradesh', 'Sohagpur', 'India'),
	(1110, 'Maharashtra', 'Mul', 'India'),
	(1111, 'Rajasthan', 'Sadulshahar', 'India'),
	(1112, 'Punjab', 'Phillaur', 'India'),
	(1113, 'Rajasthan', 'Sambhar', 'India'),
	(1114, 'Rajasthan', 'Prantij', 'India'),
	(1115, 'Uttarakhand', 'Nagla', 'India'),
	(1116, 'Punjab', 'Pattran', 'India'),
	(1117, 'Rajasthan', 'Mount Abu', 'India'),
	(1118, 'UttarPradesh', 'Reoti', 'India'),
	(1119, 'Jharkhand', 'Tenu dam-cum-Kathhara', 'India'),
	(1120, 'WestBengal', 'Panchla', 'India'),
	(1121, 'Uttarakhand', 'Sitarganj', 'India'),
	(1122, 'ArunachalPradesh', 'Pasighat', 'India'),
	(1123, 'Bihar', 'Motipur', 'India'),
	(1124, 'TamilNadu', 'O\' Valley', 'India'),
	(1125, 'WestBengal', 'Raghunathpur', 'India'),
	(1126, 'TamilNadu', 'Suriyampalayam', 'India'),
	(1127, 'Punjab', 'Qadian', 'India'),
	(1128, 'Odisha', 'Rairangpur', 'India'),
	(1129, 'DadraandNagarHaveli', 'Silvassa', 'India'),
	(1130, 'MadhyaPradesh', 'Nowrozabad (Khodargama)', 'India'),
	(1131, 'Rajasthan', 'Mangrol', 'India'),
	(1132, 'Maharashtra', 'Soyagaon', 'India'),
	(1133, 'Punjab', 'Sujanpur', 'India'),
	(1134, 'Bihar', 'Manihari', 'India'),
	(1135, 'UttarPradesh', 'Sikanderpur', 'India'),
	(1136, 'Maharashtra', 'Mangalvedhe', 'India'),
	(1137, 'Rajasthan', 'Phulera', 'India'),
	(1138, 'Karnataka', 'Ron', 'India'),
	(1139, 'TamilNadu', 'Sholavandan', 'India'),
	(1140, 'UttarPradesh', 'Saidpur', 'India'),
	(1141, 'MadhyaPradesh', 'Shamgarh', 'India'),
	(1142, 'TamilNadu', 'Thammampatti', 'India'),
	(1143, 'MadhyaPradesh', 'Maharajpur', 'India'),
	(1144, 'MadhyaPradesh', 'Multai', 'India'),
	(1145, 'Punjab', 'Mukerian', 'India'),
	(1146, 'UttarPradesh', 'Sirsi', 'India'),
	(1147, 'UttarPradesh', 'Purwa', 'India'),
	(1148, 'Bihar', 'Sheohar', 'India'),
	(1149, 'TamilNadu', 'Namagiripettai', 'India'),
	(1150, 'UttarPradesh', 'Parasi', 'India'),
	(1151, 'Gujarat', 'Lathi', 'India'),
	(1152, 'UttarPradesh', 'Lalganj', 'India'),
	(1153, 'Maharashtra', 'Narkhed', 'India'),
	(1154, 'WestBengal', 'Mathabhanga', 'India'),
	(1155, 'Maharashtra', 'Shendurjana', 'India'),
	(1156, 'TamilNadu', 'Peravurani', 'India'),
	(1157, 'Assam', 'Mariani', 'India'),
	(1158, 'UttarPradesh', 'Phulpur', 'India'),
	(1159, 'Haryana', 'Rania', 'India'),
	(1160, 'MadhyaPradesh', 'Pali', 'India'),
	(1161, 'MadhyaPradesh', 'Pachore', 'India'),
	(1162, 'TamilNadu', 'Parangipettai', 'India'),
	(1163, 'TamilNadu', 'Pudupattinam', 'India'),
	(1164, 'Kerala', 'Panniyannur', 'India'),
	(1165, 'Bihar', 'Maharajganj', 'India'),
	(1166, 'MadhyaPradesh', 'Rau', 'India'),
	(1167, 'WestBengal', 'Monoharpur', 'India'),
	(1168, 'Rajasthan', 'Mandawa', 'India'),
	(1169, 'Assam', 'Marigaon', 'India'),
	(1170, 'TamilNadu', 'Pallikonda', 'India'),
	(1171, 'Rajasthan', 'Pindwara', 'India'),
	(1172, 'UttarPradesh', 'Shishgarh', 'India'),
	(1173, 'Maharashtra', 'Patur', 'India'),
	(1174, 'Manipur', 'Mayang Imphal', 'India'),
	(1175, 'MadhyaPradesh', 'Mhowgaon', 'India'),
	(1176, 'Kerala', 'Guruvayoor', 'India'),
	(1177, 'Maharashtra', 'Mhaswad', 'India'),
	(1178, 'UttarPradesh', 'Sahawar', 'India'),
	(1179, 'TamilNadu', 'Sivagiri', 'India'),
	(1180, 'Karnataka', 'Mundargi', 'India'),
	(1181, 'TamilNadu', 'Punjaipugalur', 'India'),
	(1182, 'Tripura', 'Kailasahar', 'India'),
	(1183, 'UttarPradesh', 'Samthar', 'India'),
	(1184, 'Chhattisgarh', 'Sakti', 'India'),
	(1185, 'Karnataka', 'Sadalagi', 'India'),
	(1186, 'Bihar', 'Silao', 'India'),
	(1187, 'Rajasthan', 'Mandalgarh', 'India'),
	(1188, 'Maharashtra', 'Loha', 'India'),
	(1189, 'UttarPradesh', 'Pukhrayan', 'India'),
	(1190, 'TamilNadu', 'Padmanabhapuram', 'India'),
	(1191, 'Tripura', 'Belonia', 'India'),
	(1192, 'Mizoram', 'Saiha', 'India'),
	(1193, 'WestBengal', 'Srirampore', 'India'),
	(1194, 'Punjab', 'Talwara', 'India'),
	(1195, 'Kerala', 'Puthuppally', 'India'),
	(1196, 'Tripura', 'Khowai', 'India'),
	(1197, 'MadhyaPradesh', 'Vijaypur', 'India'),
	(1198, 'Rajasthan', 'Takhatgarh', 'India'),
	(1199, 'TamilNadu', 'Thirupuvanam', 'India'),
	(1200, 'WestBengal', 'Adra', 'India'),
	(1201, 'Karnataka', 'Piriyapatna', 'India'),
	(1202, 'UttarPradesh', 'Obra', 'India'),
	(1203, 'Gujarat', 'Adalaj', 'India'),
	(1204, 'Maharashtra', 'Nandgaon', 'India'),
	(1205, 'Bihar', 'Barh', 'India'),
	(1206, 'Gujarat', 'Chhapra', 'India'),
	(1207, 'Kerala', 'Panamattom', 'India'),
	(1208, 'UttarPradesh', 'Niwai', 'India'),
	(1209, 'Uttarakhand', 'Bageshwar', 'India'),
	(1210, 'Odisha', 'Tarbha', 'India'),
	(1211, 'Karnataka', 'Adyar', 'India'),
	(1212, 'MadhyaPradesh', 'Narsinghgarh', 'India'),
	(1213, 'Maharashtra', 'Warud', 'India'),
	(1214, 'Bihar', 'Asarganj', 'India'),
	(1215, 'Haryana', 'Sarsod', 'India');
/*!40000 ALTER TABLE `aj_state_city_mapping` ENABLE KEYS */;

-- Dumping structure for table ayantijeevan.aj_user
DROP TABLE IF EXISTS `aj_user`;
CREATE TABLE IF NOT EXISTS `aj_user` (
  `userLoginId` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `userName` varchar(25) NOT NULL,
  `userPassword` varchar(350) NOT NULL,
  `userEmail` varchar(100) DEFAULT NULL,
  `userAuthToken` varchar(100) DEFAULT NULL,
  `userApiKey` varchar(100) DEFAULT NULL,
  `status` enum('1','0') DEFAULT '0',
  `role` enum('A','U','R','M') DEFAULT 'U',
  `createdOn` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`userLoginId`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- Dumping data for table ayantijeevan.aj_user: 2 rows
DELETE FROM `aj_user`;
/*!40000 ALTER TABLE `aj_user` DISABLE KEYS */;
INSERT INTO `aj_user` (`userLoginId`, `userName`, `userPassword`, `userEmail`, `userAuthToken`, `userApiKey`, `status`, `role`, `createdOn`) VALUES
	(1, 'ralph', '280d44ab1e9f79b5cce2dd4f58f5fe91f0fbacdac9f7447dffc318ceb79f2d02', 'ralph@gmail.com', 'UiQOm3XnvaFNkb3', NULL, '1', 'A', '2018-10-30 16:08:13'),
	(2, 'ritika', '280d44ab1e9f79b5cce2dd4f58f5fe91f0fbacdac9f7447dffc318ceb79f2d02', 'ritika@gmail.com', 'TClkBzFw4fiqPbl', NULL, '1', 'U', '2018-10-30 16:08:13');
/*!40000 ALTER TABLE `aj_user` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
